# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LIL6pJd8C1n0Dr1QmbK8jjXb9t-ryHBn
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np

img = cv2.imread('image.jpg')
cv2_imshow(img)

img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2_imshow(img_gray)

invert = cv2.bitwise_not(img_gray)
cv2_imshow(invert)

blur = cv2.GaussianBlur(invert, (41, 41), 0)
cv2_imshow(blur)

invertedblur = cv2.bitwise_not(blur)
cv2_imshow(invertedblur)

sketch = cv2.divide(img_gray, invertedblur, scale=256.0)
cv2_imshow(sketch)

cv2.imwrite('sketch.jpg', sketch)